/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CaseModelService } from "../caseModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CaseModelCreateInput } from "./CaseModelCreateInput";
import { CaseModel } from "./CaseModel";
import { CaseModelFindManyArgs } from "./CaseModelFindManyArgs";
import { CaseModelWhereUniqueInput } from "./CaseModelWhereUniqueInput";
import { CaseModelUpdateInput } from "./CaseModelUpdateInput";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { DocumentWhereUniqueInput } from "../../document/base/DocumentWhereUniqueInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";
import { ResearchFindManyArgs } from "../../research/base/ResearchFindManyArgs";
import { Research } from "../../research/base/Research";
import { ResearchWhereUniqueInput } from "../../research/base/ResearchWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CaseModelControllerBase {
  constructor(
    protected readonly service: CaseModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CaseModel })
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCaseModel(
    @common.Body() data: CaseModelCreateInput
  ): Promise<CaseModel> {
    return await this.service.createCaseModel({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        deadline: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CaseModel] })
  @ApiNestedQuery(CaseModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async caseModels(@common.Req() request: Request): Promise<CaseModel[]> {
    const args = plainToClass(CaseModelFindManyArgs, request.query);
    return this.service.caseModels({
      ...args,
      select: {
        createdAt: true,
        deadline: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async caseModel(
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<CaseModel | null> {
    const result = await this.service.caseModel({
      where: params,
      select: {
        createdAt: true,
        deadline: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCaseModel(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() data: CaseModelUpdateInput
  ): Promise<CaseModel | null> {
    try {
      return await this.service.updateCaseModel({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          deadline: true,
          description: true,
          id: true,
          status: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CaseModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCaseModel(
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<CaseModel | null> {
    try {
      return await this.service.deleteCaseModel({
        where: params,
        select: {
          createdAt: true,
          deadline: true,
          description: true,
          id: true,
          status: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/documents")
  @ApiNestedQuery(DocumentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async findDocuments(
    @common.Req() request: Request,
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<Document[]> {
    const query = plainToClass(DocumentFindManyArgs, request.query);
    const results = await this.service.findDocuments(params.id, {
      ...query,
      select: {
        caseField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fileUrl: true,
        id: true,
        name: true,
        updatedAt: true,
        version: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/documents")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async connectDocuments(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        connect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/documents")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async updateDocuments(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        set: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/documents")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async disconnectDocuments(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: DocumentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      documents: {
        disconnect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        caseField: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        sentAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async connectMessages(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async updateMessages(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async disconnectMessages(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/reports")
  @ApiNestedQuery(ReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Report",
    action: "read",
    possession: "any",
  })
  async findReports(
    @common.Req() request: Request,
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReports(params.id, {
      ...query,
      select: {
        caseField: {
          select: {
            id: true,
          },
        },

        content: true,
        contentField: true,
        createdAt: true,
        id: true,
        relatedCase: true,
        reportContent: true,
        reportTitle: true,
        title: true,
        titleField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async connectReports(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        connect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async updateReports(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        set: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reports")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async disconnectReports(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reports: {
        disconnect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/researchItems")
  @ApiNestedQuery(ResearchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Research",
    action: "read",
    possession: "any",
  })
  async findResearchItems(
    @common.Req() request: Request,
    @common.Param() params: CaseModelWhereUniqueInput
  ): Promise<Research[]> {
    const query = plainToClass(ResearchFindManyArgs, request.query);
    const results = await this.service.findResearchItems(params.id, {
      ...query,
      select: {
        caseField: {
          select: {
            id: true,
          },
        },

        content: true,
        createdAt: true,
        id: true,
        savedAt: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/researchItems")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async connectResearchItems(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ResearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      researchItems: {
        connect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/researchItems")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async updateResearchItems(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ResearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      researchItems: {
        set: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/researchItems")
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async disconnectResearchItems(
    @common.Param() params: CaseModelWhereUniqueInput,
    @common.Body() body: ResearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      researchItems: {
        disconnect: body,
      },
    };
    await this.service.updateCaseModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
