/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CaseModel } from "./CaseModel";
import { CaseModelCountArgs } from "./CaseModelCountArgs";
import { CaseModelFindManyArgs } from "./CaseModelFindManyArgs";
import { CaseModelFindUniqueArgs } from "./CaseModelFindUniqueArgs";
import { CreateCaseModelArgs } from "./CreateCaseModelArgs";
import { UpdateCaseModelArgs } from "./UpdateCaseModelArgs";
import { DeleteCaseModelArgs } from "./DeleteCaseModelArgs";
import { DocumentFindManyArgs } from "../../document/base/DocumentFindManyArgs";
import { Document } from "../../document/base/Document";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ResearchFindManyArgs } from "../../research/base/ResearchFindManyArgs";
import { Research } from "../../research/base/Research";
import { User } from "../../user/base/User";
import { CaseModelService } from "../caseModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CaseModel)
export class CaseModelResolverBase {
  constructor(
    protected readonly service: CaseModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "any",
  })
  async _caseModelsMeta(
    @graphql.Args() args: CaseModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CaseModel])
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "any",
  })
  async caseModels(
    @graphql.Args() args: CaseModelFindManyArgs
  ): Promise<CaseModel[]> {
    return this.service.caseModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CaseModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "read",
    possession: "own",
  })
  async caseModel(
    @graphql.Args() args: CaseModelFindUniqueArgs
  ): Promise<CaseModel | null> {
    const result = await this.service.caseModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CaseModel)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "create",
    possession: "any",
  })
  async createCaseModel(
    @graphql.Args() args: CreateCaseModelArgs
  ): Promise<CaseModel> {
    return await this.service.createCaseModel({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CaseModel)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "update",
    possession: "any",
  })
  async updateCaseModel(
    @graphql.Args() args: UpdateCaseModelArgs
  ): Promise<CaseModel | null> {
    try {
      return await this.service.updateCaseModel({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CaseModel)
  @nestAccessControl.UseRoles({
    resource: "CaseModel",
    action: "delete",
    possession: "any",
  })
  async deleteCaseModel(
    @graphql.Args() args: DeleteCaseModelArgs
  ): Promise<CaseModel | null> {
    try {
      return await this.service.deleteCaseModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Document], { name: "documents" })
  @nestAccessControl.UseRoles({
    resource: "Document",
    action: "read",
    possession: "any",
  })
  async findDocuments(
    @graphql.Parent() parent: CaseModel,
    @graphql.Args() args: DocumentFindManyArgs
  ): Promise<Document[]> {
    const results = await this.service.findDocuments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Message], { name: "messages" })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @graphql.Parent() parent: CaseModel,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Report], { name: "reports" })
  @nestAccessControl.UseRoles({
    resource: "Report",
    action: "read",
    possession: "any",
  })
  async findReports(
    @graphql.Parent() parent: CaseModel,
    @graphql.Args() args: ReportFindManyArgs
  ): Promise<Report[]> {
    const results = await this.service.findReports(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Research], { name: "researchItems" })
  @nestAccessControl.UseRoles({
    resource: "Research",
    action: "read",
    possession: "any",
  })
  async findResearchItems(
    @graphql.Parent() parent: CaseModel,
    @graphql.Args() args: ResearchFindManyArgs
  ): Promise<Research[]> {
    const results = await this.service.findResearchItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: CaseModel): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
